library(knitr)
library(XML)
library(RCurl)
library(shiny)
library(plotly)
library(ggplot2)
library(plyr)
library(dplyr)
library(reshape2)
library(rworldmap)
library(maps)
library(ggmap)
library(classInt)
library(RColorBrewer)
library(devtools)
library(maptools)
library(rgeos)
library(scales)
library(stringr)
library(gmt)
library(graphics)
library(mapproj)
library(geosphere)
library(sp)


# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("vizualizacija/uvoz_zemljevidov.R", encoding = "UTF-8")

